/**
 * 模板Mock数据 - 仅供开发和设计阶段使用
 *
 * ⚠️ 警告：此文件仅用于开发环境Mock数据
 * 生产环境必须使用真实API，禁止导入此文件
 *
 * @deprecated 正式发布前应移除此文件的使用
 */

import {
  Template,
  TemplateCategory,
  TemplateDifficulty,
  TargetPlatform,
} from "@/types/template";

/**
 * Mock模板数据
 * 用途：开发环境、UI设计验证、Storybook展示
 */
export const MOCK_TEMPLATES: Template[] = [
  {
    id: "ecommerce-shop",
    name: "电商购物平台",
    description: "完整的在线购物平台，支持商品展示、购物车、订单管理",
    detailedDescription:
      "功能完整的电商平台模板，包含商品浏览、搜索、分类、购物车、订单管理、支付集成等核心功能。适合快速搭建在线商城。",
    category: TemplateCategory.ECOMMERCE,
    difficulty: TemplateDifficulty.COMPLEX,
    platforms: [TargetPlatform.ANDROID, TargetPlatform.IOS, TargetPlatform.WEB],
    features: [
      "商品展示和搜索",
      "购物车管理",
      "订单处理",
      "支付集成",
      "用户认证",
      "商品评价",
    ],
    coverImage: "/templates/ecommerce.jpg",
    screenshots: [],
    techStack: ["Kotlin Multiplatform", "Supabase", "Stripe"],
    usageCount: 1234,
    rating: 4.8,
    createdAt: "2025-01-10",
    tags: ["电商", "支付", "热门"],
  },
  {
    id: "social-network",
    name: "社交网络",
    description: "类似微博的社交平台，支持动态发布、关注、点赞评论",
    detailedDescription:
      "现代化社交网络应用模板，包含用户个人主页、动态发布、图片上传、关注系统、点赞评论、私信聊天等功能。",
    category: TemplateCategory.SOCIAL,
    difficulty: TemplateDifficulty.COMPLEX,
    platforms: [TargetPlatform.ANDROID, TargetPlatform.IOS],
    features: ["动态发布", "关注系统", "点赞评论", "私信聊天", "图片上传", "个人主页"],
    coverImage: "/templates/social.jpg",
    screenshots: [],
    techStack: ["Kotlin Multiplatform", "Supabase", "WebSocket"],
    usageCount: 987,
    rating: 4.6,
    createdAt: "2025-01-08",
    tags: ["社交", "实时通讯"],
  },
  {
    id: "todo-app",
    name: "任务管理工具",
    description: "简洁高效的待办事项管理，支持分类、提醒、统计",
    detailedDescription:
      "功能强大的任务管理应用，支持任务分类、优先级设置、到期提醒、完成统计、数据同步等功能。",
    category: TemplateCategory.TOOLS,
    difficulty: TemplateDifficulty.SIMPLE,
    platforms: [TargetPlatform.ANDROID, TargetPlatform.IOS, TargetPlatform.WEB, TargetPlatform.WECHAT],
    features: ["任务分类", "优先级管理", "提醒通知", "完成统计", "数据同步"],
    coverImage: "/templates/todo.jpg",
    screenshots: [],
    techStack: ["Kotlin Multiplatform", "Supabase"],
    usageCount: 2345,
    rating: 4.9,
    createdAt: "2025-01-12",
    tags: ["工具", "简单", "热门"],
  },
  {
    id: "blog-cms",
    name: "博客内容管理系统",
    description: "支持Markdown编写的博客系统，包含文章管理、分类标签",
    detailedDescription:
      "专业的博客CMS系统，支持Markdown编辑、文章分类、标签管理、评论系统、SEO优化等功能。",
    category: TemplateCategory.CONTENT,
    difficulty: TemplateDifficulty.MEDIUM,
    platforms: [TargetPlatform.WEB],
    features: ["Markdown编辑器", "文章分类", "标签管理", "评论系统", "SEO优化", "草稿箱"],
    coverImage: "/templates/blog.jpg",
    screenshots: [],
    techStack: ["Next.js", "Supabase", "TailwindCSS"],
    usageCount: 756,
    rating: 4.5,
    createdAt: "2025-01-05",
    tags: ["内容", "博客", "Markdown"],
  },
  {
    id: "online-course",
    name: "在线课程平台",
    description: "在线教育平台，支持课程管理、视频播放、作业系统",
    detailedDescription:
      "完整的在线教育解决方案，包含课程管理、视频播放、作业提交、成绩统计、师生互动等功能。",
    category: TemplateCategory.EDUCATION,
    difficulty: TemplateDifficulty.COMPLEX,
    platforms: [TargetPlatform.ANDROID, TargetPlatform.IOS, TargetPlatform.WEB],
    features: ["课程管理", "视频播放", "作业系统", "成绩统计", "师生互动", "学习进度"],
    coverImage: "/templates/course.jpg",
    screenshots: [],
    techStack: ["Kotlin Multiplatform", "Supabase", "Video.js"],
    usageCount: 543,
    rating: 4.7,
    createdAt: "2025-01-03",
    tags: ["教育", "视频", "互动"],
  },
  {
    id: "chat-app",
    name: "即时通讯应用",
    description: "实时聊天应用，支持单聊、群聊、文件传输",
    detailedDescription:
      "功能完整的即时通讯应用，支持文字聊天、图片视频发送、文件传输、群组管理、消息加密等。",
    category: TemplateCategory.SOCIAL,
    difficulty: TemplateDifficulty.COMPLEX,
    platforms: [TargetPlatform.ANDROID, TargetPlatform.IOS],
    features: ["实时聊天", "群组管理", "文件传输", "消息加密", "离线消息", "已读回执"],
    coverImage: "/templates/chat.jpg",
    screenshots: [],
    techStack: ["Kotlin Multiplatform", "Supabase", "WebSocket"],
    usageCount: 1456,
    rating: 4.8,
    createdAt: "2025-01-11",
    tags: ["社交", "实时通讯", "热门"],
  },
  {
    id: "fitness-tracker",
    name: "健身追踪工具",
    description: "记录运动数据、制定健身计划、统计健康指标",
    detailedDescription:
      "专业的健身追踪应用，记录运动数据、制定训练计划、统计健康指标、社区分享等功能。",
    category: TemplateCategory.TOOLS,
    difficulty: TemplateDifficulty.MEDIUM,
    platforms: [TargetPlatform.ANDROID, TargetPlatform.IOS],
    features: ["运动记录", "训练计划", "健康统计", "社区分享", "卡路里计算", "目标设定"],
    coverImage: "/templates/fitness.jpg",
    screenshots: [],
    techStack: ["Kotlin Multiplatform", "Supabase", "Charts"],
    usageCount: 678,
    rating: 4.4,
    createdAt: "2025-01-07",
    tags: ["工具", "健康", "运动"],
  },
  {
    id: "note-taking",
    name: "笔记应用",
    description: "支持富文本、标签分类的笔记工具，可云端同步",
    detailedDescription:
      "强大的笔记应用，支持富文本编辑、标签分类、全文搜索、云端同步、多端协作等功能。",
    category: TemplateCategory.TOOLS,
    difficulty: TemplateDifficulty.SIMPLE,
    platforms: [TargetPlatform.ANDROID, TargetPlatform.IOS, TargetPlatform.WEB],
    features: ["富文本编辑", "标签分类", "全文搜索", "云端同步", "多端协作", "离线访问"],
    coverImage: "/templates/notes.jpg",
    screenshots: [],
    techStack: ["Kotlin Multiplatform", "Supabase", "Quill"],
    usageCount: 1890,
    rating: 4.7,
    createdAt: "2025-01-09",
    tags: ["工具", "笔记", "简单"],
  },
  {
    id: "news-aggregator",
    name: "新闻聚合阅读器",
    description: "订阅RSS源、个性化推荐、离线阅读",
    detailedDescription:
      "智能新闻阅读器，支持RSS订阅、个性化推荐、分类筛选、离线阅读、跨平台同步等功能。",
    category: TemplateCategory.CONTENT,
    difficulty: TemplateDifficulty.MEDIUM,
    platforms: [TargetPlatform.ANDROID, TargetPlatform.IOS, TargetPlatform.WEB],
    features: ["RSS订阅", "个性化推荐", "分类筛选", "离线阅读", "收藏夹", "跨平台同步"],
    coverImage: "/templates/news.jpg",
    screenshots: [],
    techStack: ["Kotlin Multiplatform", "Supabase", "RSS Parser"],
    usageCount: 432,
    rating: 4.3,
    createdAt: "2025-01-04",
    tags: ["内容", "阅读", "RSS"],
  },
  {
    id: "recipe-book",
    name: "电子食谱",
    description: "收藏和分享食谱，支持步骤详解、食材清单",
    detailedDescription:
      "美食爱好者的最佳选择，收藏和分享食谱、步骤详解、食材清单、烹饪计时器、营养计算等功能。",
    category: TemplateCategory.OTHER,
    difficulty: TemplateDifficulty.SIMPLE,
    platforms: [TargetPlatform.ANDROID, TargetPlatform.IOS],
    features: ["食谱收藏", "步骤详解", "食材清单", "烹饪计时器", "营养计算", "社区分享"],
    coverImage: "/templates/recipe.jpg",
    screenshots: [],
    techStack: ["Kotlin Multiplatform", "Supabase"],
    usageCount: 321,
    rating: 4.5,
    createdAt: "2025-01-06",
    tags: ["生活", "美食", "简单"],
  },
  {
    id: "quiz-app",
    name: "在线题库系统",
    description: "刷题练习、错题本、智能组卷",
    detailedDescription:
      "专业的题库系统，支持刷题练习、错题本管理、智能组卷、成绩分析、知识点统计等功能。",
    category: TemplateCategory.EDUCATION,
    difficulty: TemplateDifficulty.MEDIUM,
    platforms: [TargetPlatform.ANDROID, TargetPlatform.IOS, TargetPlatform.WEB],
    features: ["题库管理", "错题本", "智能组卷", "成绩分析", "知识点统计", "模拟考试"],
    coverImage: "/templates/quiz.jpg",
    screenshots: [],
    techStack: ["Kotlin Multiplatform", "Supabase"],
    usageCount: 891,
    rating: 4.6,
    createdAt: "2025-01-10",
    tags: ["教育", "题库", "考试"],
  },
  {
    id: "calendar-scheduler",
    name: "日历日程管理",
    description: "日历视图、事件提醒、日程共享",
    detailedDescription:
      "功能全面的日历应用，支持多视图（日/周/月）、事件提醒、日程共享、重复事件、时区管理等。",
    category: TemplateCategory.TOOLS,
    difficulty: TemplateDifficulty.MEDIUM,
    platforms: [TargetPlatform.ANDROID, TargetPlatform.IOS, TargetPlatform.WEB],
    features: ["多视图日历", "事件提醒", "日程共享", "重复事件", "时区管理", "日程导出"],
    coverImage: "/templates/calendar.jpg",
    screenshots: [],
    techStack: ["Kotlin Multiplatform", "Supabase", "FullCalendar"],
    usageCount: 1123,
    rating: 4.7,
    createdAt: "2025-01-08",
    tags: ["工具", "日历", "日程"],
  },
];
// [CHECKPOINT:FILE_END:templates.mock.ts:SUCCESS]
